project:
  type: website
  output-dir: _site
  render:
    - "*.qmd"
    - "trackers/*.qmd"
  resources:
    - "assets/**"
    - "pic.png"

website:
  title: "Michal Ovádek"
  site-url: "https://michalovadek.github.io"
  open-graph: true
  navbar:
    left:
      - href: home.qmd
        text: Home

format:
  html:
    theme:
      light: [zephyr, assets/style.scss]
      dark:  [darkly, assets/style.scss]
    include-in-header: assets/header.html
    toc: false
    smooth-scroll: true

execute:
  freeze: auto
